### ISSUE TITLE
DDNS Provider Strato

### ISSUE THREAD

**Issue by Shodanki** [stephdl/dev#1]
Can You Please Create an Template for your DDCLIENT for Strato:

Like:
protocol=dyndns2
use=web
ssl=yes
server=dyndns.strato.com/nic/update
login=example-domain.de
password='passwort'
example-domain.de

Kindly Regards
Shodan

**Comment by stephdl** [comment]
Hi Shodan

I can be wrong but I believe that the dynamic dns service is not free and you must purchase a service. I would like to provide a preconfigured service when the usage is free like for the dtns.net

This is what I read in their FAQ : 
 https://www.strato.fr/faq/article/1835/Quels-parametres-puis-je-definir-dans-la-boite-de-dialogue-de-configuration-Dynamic-DNS-DynDNS.html

I did two ways to configure when the service is not preconfigured, the custom fields and the custom template ways. I hope that you can use strato like this  ?

**Comment by Shodanki** [comment]
You are right it is "paid" so you need at least a Domain from Strato but as it is Germans biggest Player in this market there are many people use it.

The Problem for the Configuration lays here ->server   **dyndns.strato.com/nic/update**
as this is not an FQDN  you cannot add this server as custom.
I can provide you with a Testing Domain and Password or beta test for you :).

kindly regards

**Comment by stephdl** [comment]
update to 1.0.5 in a few time and report back if all is right with strato

**Comment by Shodanki** [comment]
works perfect :)
Kindly Regards and Best Wishes for your quick reaction you are my hero ;)

**Comment by stephdl** [comment]
cool 

closing as per comment above
