### ISSUE TITLE
https://wiki.nethserver.org/doku.php?id=mariadb102&s[]=mariadb

### ISSUE THREAD

**Issue by micronator** [stephdl/dev#10]
Salut Stéphane,

Pour PHP72 j'ai ceci qui fonctionne très bien: http://appdev.oit.umn.edu/2015/02/11/scl/
```
cat > /etc/profile.d/activer-php72.sh <<'EOT'
#!/bin/bash
source /opt/remi/php72/enable
if [[ "$X_SCLS" != *php72* ]]; then
src="`scl enable php72 'echo $X_SCLS'`"
pkgs=(${src// / })
uniq=($(printf "%s\n" "${pkgs[@]}" | sort -u));
export X_SCLS="${uniq[@]}"
fi
EOT
```

Mais ça fonctionne pas avec MariaDB102 et je sais pas pourquoi, je crois que c'est à cause que ça s'appelle mysql102?

```
cat > /etc/profile.d/activer-rh-mariadb102.sh <<'EOT'
#!/bin/bash
source /opt/rh/rh-mariadb102/enable
if [[ "$X_SCLS" != *rh-mariadb102* ]]; then
src="`scl enable rh-mariadb102 'echo $X_SCLS'`"
pkgs=(${src// / })
uniq=($(printf "%s\n" "${pkgs[@]}" | sort -u));
export X_SCLS="${uniq[@]}"
fi
EOT
```

Tes howtos m'impressionnent,

Michel-André

**Comment by stephdl** [comment]
Ola !

En fait si je comprends bien tu souhaites remplacer mariadb officiel par mariadb scl, à priori je ne suis pas tres chaud pour cela, je peux compendre pour php, python, bien que pas mal de bug puisse sortir, mais pour remplacer le sgbd, j'ai un peu peur.

Priori j'ai prevu un systeme de backup pour mariadb, un clone de l'existant, du coup tu devrais pas avoir besoin de remplacer la version officielle par la version scl, juste utiliser la scl à coté de l'officielle.

Dis moi si je suis a coté de la plaque

**Comment by stephdl** [comment]
je suppose que le mysql102 dont tu parles provient de la ?

https://github.com/stephdl/nethserver-rh-mariadb102/blob/ns7/root/usr/bin/mysql102

**Comment by stephdl** [comment]
avant de faire ton trick

```
[root@ns7loc14 ~]# mysql --version
mysql  Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1
```

apres avoir fait ton trick et redemarré ma vm (simple cp and paste)

```
[root@ns7loc14 ~]# mysql --version
mysql  Ver 15.1 Distrib 10.2.8-MariaDB, for Linux (x86_64) using  EditLine wrapper
```

donc cela fonctionne :D

Je vais fermé ce thread, pour le support le forum de la communauté est le mieux placé....à plus de l'autre coté.
