### ISSUE TITLE
Request for Clarification: OCSInventory-NG > Settings

### ISSUE THREAD

**Issue by ThePhoenixRiseth** [stephdl/dev#11]
On the NethServer Wiki, there is info for installing OCS Inventory (https://wiki.nethserver.org/doku.php?id=ocsinventory).  I followed the instructions but I am not able to access the web page at https://IP/ocreports.  However this is not working with my IP.  I want to check the settings, but the Settings info on the page begins with a config command.  My system is saying command config not found.  What is the proper way to update the settings?  Is there a specific directory I need to be in to run the command?

**Comment by stephdl** [comment]
hi mate

Thank for reporting a typo in the wiki, please go to https://ip/ocsreports
