### ISSUE TITLE
whitelist domain names

### ISSUE THREAD

**Issue by pagaille** [stephdl/dev#13]
Hi Steph,

Following that page : https://blog.rimuhosting.com/2017/02/24/whitelist-your-own-computer-in-fail2ban/ it looks possible to whitelist a domain name instead of an IP. However, nethserver's UI (cockpit and server-manager) don't accept FQDN. Is it wanted ? 

That could really be useful to whitelist a dyndns address...

Txs

Matt

**Comment by stephdl** [comment]
Please would you mind to open a thread on the community forum, nethserver-fail2ban is an official module now :)

set closed
