### ISSUE TITLE
Missing 'Web Statistic' panel for awstats in the Management category

### ISSUE THREAD

**Issue by ResponsableSeguridadAudifilm** [stephdl/dev#14]
Hello,
I have a  NS 7.6.1810 running were I installed your repositori and after you awstats module looking to have email statistics of the system.

Everything installed fine but I see no "Web Statistic" panel in the Management tree, as your documentation says. I also restarted the httpd-admin, but I see nothing new.

What could I look at, please?
Thanks

[root@mailserver ~]# yum install nethserver-awstats --enablerepo=stephdl
...
Installed:
  nethserver-awstats.noarch 0:0.1.12-1.ns7.sdl
Dependency Installed:
  awstats.noarch 0:7.7-1.el7            dejavu-serif-fonts.noarch 0:2.33-6.el7     fltk.x86_64 0:1.3.4-1.el7           htmldoc.x86_64 0:1.8.28-4.el7    libXcursor.x86_64 0:1.1.15-1.el7
  libXinerama.x86_64 0:1.1.3-2.1.el7    libfontenc.x86_64 0:1.1.3-3.el7            mesa-libGLU.x86_64 0:9.0.0-4.el7    perl-CGI.noarch 0:3.63-4.el7     perl-FCGI.x86_64 1:0.74-8.el7
  perl-Geo-IP.x86_64 0:1.43-3.el7       perl-Net-IP.noarch 0:1.26-4.el7            perl-Switch.noarch 0:2.16-7.el7     t1utils.x86_64 0:1.37-6.el7      ttf2pt1.x86_64 0:3.4.4-17.el7
  urw-fonts.noarch 0:2.4-16.el7         xorg-x11-font-utils.x86_64 1:7.5-21.el7
Complete!

**Comment by ResponsableSeguridadAudifilm** [comment]
I see that there are 2 awstats modules:

[root@mailserver awstats]# rpm -qa | grep awstats
awstats-7.7-1.el7.noarch
nethserver-awstats-0.1.12-1.ns7.sdl.noarch

**Comment by stephdl** [comment]
you do not have a `Awstats Statistic` in the `Configuration` menu of netgui ?

![Screenshot_2019-09-16 Example Org - Awstats Statistic](https://user-images.githubusercontent.com/3164851/64984457-328f8680-d8c3-11e9-9e92-bc5e2c329142.png)

**Comment by ResponsableSeguridadAudifilm** [comment]
Yes, thanks very much!!
I was looking at the “Management” category, as your page says:
https://wiki.nethserver.org/doku.php?id=awstats#usage
"You have a panel 'Web Statistic' in the Management category, with two available tabs..."

I see now it are on Configuration menu :)
Thanks!! I'll try it now.

**Comment by stephdl** [comment]
set closed as resolved per comment above
