### ISSUE TITLE
Nethserver wordpress Wiki page error in signal-event statement

### ISSUE THREAD

**Issue by maja2020** [stephdl/dev#15]
The auto updater version shows this line: 
`signal-event nethserver-wordpress-AutoUpdater`

Did not work, the /etc/e-mith/events folder, showed me the correct statement 
`signal-event nethserver-wordpress-AutoUpdater-update` 
works.

**Comment by stephdl** [comment]
@maja2020 thank to bring it up, I modified the documentation and the code, now you can also use 

`signal-event nethserver-wordpress-update`

https://wiki.nethserver.org/doku.php?id=wordpress#wordpress-autoupdater
