### ISSUE TITLE
nethserver-crontabmanager command error: The validation has been failed: This command line is not allowed : [ "\\" ]

### ISSUE THREAD

**Issue by menteora** [stephdl/dev#16]
Hi @stephdl , thanks for your work on nethserver!

I've trying to execute this command on crontabmanager

`/usr/bin/rm -rdf /var/lib/nethserver/ibay/temp/* /var/lib/nethserver/ibay/temp/.* 2> /dev/null`

Validation raise this error :

`The validation has been failed: This command line is not allowed : [ "\\" ]`

I've tried a lot of similar commands without success. This command work on command line.

Can you help me?
Thanks a lot.

Here's screenshot: 
![image](https://user-images.githubusercontent.com/3657745/79444322-53e05e80-7fdb-11ea-95e2-6e41ebf00d2d.png)

**Comment by stephdl** [comment]
of course I can help you, I do some validation to be sure that a command could not be escaped, so in short what you need here is to make a bash file 

#!/usr/bin/bash
/my/bash/command 

save and chmod u+x or chmod a+x

then write the path of the bash file in your cron command

**Comment by stephdl** [comment]
maybe I need to do an inline help to explain this

**Comment by menteora** [comment]
Perfect! Thank you for your very fast response!
I'll try.
L.
