### ISSUE TITLE
nethserver-stephdl disables other 3th party repoistories on install or update

### ISSUE THREAD

**Issue by markVnl** [stephdl/dev#18]
Hi Stephane, 

Nothing serious,  just a thing to revisit after your vacation. (hope it is good)

A side affect of the action [stephdl_enablerepo](https://github.com/stephdl/nethserver-stephdl/blob/ns7/root/etc/e-smith/events/actions/stephdl_enablerepo) is other 3th-party repositories who do **not** hook in to the template `/etc/nethserver/eorepo.conf` or are enabled by the user (`config setprop subscription ExtraRepositories repoA,repoB,repoC`) are disabled at install and every update of nethserver-stephdl.

For sure this also happens with an update of the nethserver-subscription (and a nethsever point release);
However I do not think it is necessary to run `signal-event software-repos-save`. 
Your repository is enabled by [default](https://github.com/stephdl/nethserver-stephdl/blob/8ac3fc8e6140d7b8fcad89538d079891c7a35005/root/etc/yum.repos.d/stephdl.repo#L5) and stay's enabled after `software-repos-save`

What is the reason to run it explicitly? 

cc // @danb35 as his repository is affected by this.

**Comment by stephdl** [comment]
every repository enabled by the yum definition like [my repository](https://github.com/stephdl/nethserver-stephdl/blob/8ac3fc8e6140d7b8fcad89538d079891c7a35005/root/etc/yum.repos.d/stephdl.repo#L5) are disabled after the event, we have to declare them 

I am not sure to understand 

please check 

```
[root@ns7 ~]# cat /etc/nethserver/eorepo.conf 
# ================= DO NOT MODIFY THIS FILE =================
# 
# Manual changes will be lost when this file is regenerated.
#
# Please read the developer's guide, which is available
# at NethServer official site: https://www.nethserver.org
#
# 
#
# This file is read by software-repos-save event
#
# Listed repositories will be enabled, everything else will be disabled
#
# Blank lines and lines beginning with "#" are ignored
#

ce-base
ce-updates
ce-extras
ce-sclo-rh
ce-sclo-sclo
epel
nethserver-base
nethserver-updates
nethforge
stephdl
```

**Comment by markVnl** [comment]
my concern is the` software-repos-save` event is not called often, not really sure it is run on a `nethserver-subscrition` update. 
The only thing I know for sure: it runs if you `subscribe` your system and at `system-init`, 
pretty sure:  it runs after a nethserver point release. 

Users of non subscription installs experience their 3th-party repo (--not yours) are disabled once a while, for them out of the blue..

**Comment by stephdl** [comment]
if I understand correctly, but if not please correct or explain differently.

After the installation of my rpm you state that some other external repositories are disabled because I run the event software-repo-save, if I understand correctly I would say it is a core feature of NethServer, only declared repository [like I do](https://github.com/stephdl/nethserver-stephdl/blob/ns7/root/etc/e-smith/templates/etc/nethserver/eorepo.conf/45stephdl) by pushing a repository name in an array are enabled, if not others are disabled.

This is out of my hand and needs to be known by developers, this have been added with the development to block the update to a minor centos release (eg 7.8 to 7.9)

**Comment by markVnl** [comment]
> if I understand correctly, but if not please correct or explain differently.

Yes you understand correctly ... or at least this is how I understand it form observed behavior :)

As said the `software-repos-save` event is not run much so one can explain / understand it when 7.10 arrives,
and as I observe it: it not necessary to run this at installation or update of `nethserver-stephdl`.

**Comment by stephdl** [comment]
>and as I observe it: it not necessary to run this at installation or update of nethserver-stephdl.

How can we do it differently ?

I have not much update on this rpm :-?

**Comment by markVnl** [comment]
> How can we do it differently ?

maybe we should ask Davide when and why `software-repos-save` supposed to  run,;
especially on non-subscription systems...

As far as I can see one does not need to run this to install a yum repository configuration,
so my suggestion is to omit `stephdl_enablerepo ` all together , but keep pushing your repository to the array for `/etc/nethserver/eorepo.conf`

**Comment by stephdl** [comment]
no your proposal wont work, if my repository is not listed inside eorepo.conf then it will be disabled when the event software-repos-save will be triggered

Maybe if I only expand the template eorepo.conf it could work but it is not sure.

**Comment by markVnl** [comment]
did **not** suggest to omit : 
https://github.com/stephdl/nethserver-stephdl/blob/ns7/root/etc/e-smith/templates/etc/nethserver/eorepo.conf/45stephdl

suggested to omit:
https://github.com/stephdl/nethserver-stephdl/blob/ns7/root/etc/e-smith/events/actions/stephdl_enablerepo

**Comment by stephdl** [comment]
Well probably a nofix, I still do not know if I will do something, but what I am sure that not only nethserver-stephdl is concerned :|

https://github.com/search?q=user%3Astephdl+software-repos-save&type=code

**Comment by markVnl** [comment]
Oke, just fine by me.
 Can not explain it better and only repeat myself:

What is the reason to run software-repos-save explicitly?

**Comment by stephdl** [comment]
> What is the reason to run software-repos-save explicitly?

Be sure that my repository won't be disabled by the event above, not time yet to test another way :(

**Comment by stephdl** [comment]
I would like to let this issue opened, I can provide some tests. I am just back from holidays

**Comment by markVnl** [comment]
As said, nothing serious :)

**EDIT:** Hope you enjoined your holidays! 

(simply bump this up, and I'll get notified and happy to assist if I can)

**Comment by stephdl** [comment]
yeah bike, hiking, canyoning, via ferrata in aragon and picos of europa (spain)...that was a good time :D

**Comment by stephdl** [comment]
get time, will fix it and for other repo too

**Comment by stephdl** [comment]
https://github.com/stephdl/nethserver-stephdl/pull/3
https://github.com/stephdl/nethserver-wapt/pull/1
https://github.com/stephdl/nethserver-BackupPC4/pull/2
https://github.com/stephdl/nethserver-bareos/pull/5
https://github.com/stephdl/nethserver-php-scl/pull/3

I think we can close this issue, what do you think ?

released in my repo

**Comment by markVnl** [comment]
Beautiful ,

It is going to make a lot of people less confused! 

Thanks
