### ISSUE TITLE
transmission listen port is not correctly opened

### ISSUE THREAD

**Issue by ghost** [stephdl/dev#2]
In your nethserver-transmission module, there is a bit of a misconfiguation.

You have port 51413 listed as public, but since it is in the transmission=configuration, it does not actually open the port. Nethserver appears to only recognize the port values stored in a service, such as transmission-daemon=service.

The 9091 port also doesn't even need to be in the service, since its local it will be forwarded through the apache proxy.

Note: Transmission still works with port 51413 closed, but you cannot accept incoming connections.

**Comment by stephdl** [comment]
let me check in this issue, thank for reporting

**Comment by stephdl** [comment]
Ok, we cannot use service here because  you will see a red warning disabled for transmission in the network service page. We must  find another way like open directly the port in shorewall. I supppose that you use the ns7 version of nethserver ?

**Comment by ghost** [comment]
Yes, I am using NS7. To open the port I just created a new service on the "Firewall Objects" page, then let that service through the firewall on the "Firewall rules" page.

FYI, transmission can still seed with the port closed (passive mode), but if it is fully open (active mode), you can connect to many more seeders, and potentially download faster. Source: [Transmission says port is closed but seeding is happening - on askubuntu](https://askubuntu.com/questions/405487/transmission-says-port-is-closed-but-seeding-is-happening/405496#405496)

Leaving the port closed is more secure, in that someone cannot determine you are running transmission from pinging the port. After thinking on it,  leaving your transmission module "as is" is best for security. If one wants it open, they can just open it that way I did.

**Comment by stephdl** [comment]
update transmission, the port should be opened now, valid for ns6 and ns7. In order to test you can remove first the key transmission

`config delete transmission`

then upgrade

**Comment by ghost** [comment]
Can confirm that 1.1.6-1 opens up the port correctly.

**Comment by stephdl** [comment]
nice :)

For security matter you can set to random the peer port, each time the service will start it will assign a new port, of course you must have an upnp service running on your router.

**Comment by stephdl** [comment]
set to closed
