### ISSUE TITLE
Instructions for dd-cleint on Nethserver say use vim, but vim is not found

### ISSUE THREAD

**Issue by dutch55** [stephdl/dev#20]
https://wiki.nethserver.org/doku.php?id=module:ddclient describes how to add a custom provider fragment, but the following command line fails with command not found:
vim /etc/e-smith/templates/etc/ddclient.conf/30Custom

**Comment by stephdl** [comment]
do you have vim installed ?

**Comment by dutch55** [comment]
> do you have vim installed ?

I do now. Maybe I am so far out of the mainstream user it isn't worth catering to me. I used to write software long ago, But I only have to use a Linux command once in years, and have forgotten how to use emacs or VI, let alone use vim. But if you do want to make your software easier to consume by people like me, you could do two things: add the command to install vim, and add the save/exit commands to save the file. I went hunting for both, and created the file,

**Comment by stephdl** [comment]
Sure, I could use nano as example but it was not much exiting, Happy that you fix your issue, let's close it
