### ISSUE TITLE
GLPI Inventory Plugin

### ISSUE THREAD

**Issue by emagdybob** [stephdl/dev#21]
GLPI Inventory
-General setup
-Agents modules

I installed GLPI inventory plugins but every time set agent for snmp inventory  I got the error "You don't have permission to perform this action"
I checked the profiles for super admin it have full permission checked for GLPI inventory
appreciate your support 
Thanks
![Capture](https://user-images.githubusercontent.com/115551178/216020460-2f5a2239-944d-448e-9f10-812325680425.PNG)
![Capture2](https://user-images.githubusercontent.com/115551178/216020467-98f86c1b-1b69-46f9-b238-e167cb88f291.PNG)

**Comment by stephdl** [comment]
hello

could you please open a thread on the forum of the community, https://community.nethserver.org/

you will have expert to help you 

I am just the developer/packager, maybe I am not a power user

For now I close this issue

**Comment by emagdybob** [comment]
thanks
