### ISSUE TITLE
Typo in Php-SCL page

### ISSUE THREAD

**Issue by dcrobertson01** [stephdl/dev#3]
Hi - page at https://wiki.nethserver.org/doku.php?id=php-scl has an error - trips up those of us more used to apt than yum :-)

  yum list available php* --disablerepo=* --enablerepo=remi-safe

should read 

  yum list available php\\* --disablerepo=* --enablerepo=remi-safe

at least for NS 7

prob a markdown formatting thing - you need two \\'s for one to show up :-)

**Comment by stephdl** [comment]
hi 

Thank for reporting, the command was workable but I added your change. As a side note you can create a wiki account and modify yourself when you see a typo or if you want to add your user experience and knowledge.

closed
