### ISSUE TITLE
Installed but missing interface

### ISSUE THREAD

**Issue by unmanagedtn** [stephdl/dev#4]
Its installed but I cant find the panel anywhere in NS7 ..... Any ideas?

**Comment by stephdl** [comment]
sorry, what is lts ?

**Comment by unmanagedtn** [comment]
i figured it out.. 🤣 but on android it is doubling up characters root turns into rroott, the terminal installed from your repo...

**Comment by stephdl** [comment]
you spoke  about https://wiki.nethserver.org/doku.php?id=shellinabox

what is the ouput of 

`rpm -qa | grep shellinabox`

**Comment by stephdl** [comment]
close please repoen if needed

**Comment by unmanagedtn** [comment]
the error is the images on setting different directory were not understood...

**Comment by stephdl** [comment]
sorry, could you reformulate or explain differently I did not catch you
