### ISSUE TITLE
FTP Updates of WP 

### ISSUE THREAD

**Issue by unmanagedtn** [stephdl/dev#6]
Wordpress wont update via FTP giving errors on permissions but not any detail on how to fix it...
If you cant do it via FTP is it safe to do it the manual way?

**Comment by stephdl** [comment]
Definitively if you want to update wordpress, two ways

- wait the next rpm from epel
- or create the mysql database and install manually wordpress in a virtualhost

The rpm doesn't allow manual upgrade, this to protect the next rpm upgrade

BTW, why are you so hurry to upgrade wordpress, I even do not sure it is a huge jump ?

**Comment by stephdl** [comment]
After that for any
