### ISSUE TITLE
MariaDB10x vs MySQL and the localhost

### ISSUE THREAD

**Issue by JOduMonT** [stephdl/dev#8]
Hi Steph;

#### CONTEXT
I'm not sure it is an issue but
I just install `yum install nethserver-rh-mariadb102`
and being very careful to not install mysql and/or nethserver-mysql
_but also installed `nethserver-automysqlbackup` which is maybe the one also installed mysql, ..._

#### SITUATION
When I use adminer to connect I was, at the beginning mesmerism
because ...
when I was login in via :
`localhost:3312` and `localhost` is connecting to **mysql**
`127.0.0.1:3312` is connecting to **mariadb**

it took me a while to realize I wasn't in the same engine because both was using the same password, which I found in `/root/.my.cnf`

#### EXPECTATION ??
Anyway; if I'll installed both mysql and mariadb, I would expect **mysql** only answering to `localhost` and not to `localhost:3312`, but then that would probably means mysql will not be reachable through his socket '/var/lib/mysql/mysql.sock'

##### ALSO
I notice the backupuser is not in mariadb, should I do something to make `nethserver-automysqlbackup` works ?

if so; where I could fine or define the backupuser password ?

Cheer!

Jonathan

**Comment by stephdl** [comment]
sorry for the time, I was in holidays...let me search

**Comment by stephdl** [comment]
> I notice the backupuser is not in mariadb, should I do something to make nethserver-automysqlbackup works ?
> 
> if so; where I could fine or define the backupuser password ?
https://github.com/stephdl/nethserver-automysqlbackup/blob/ns7/root/etc/e-smith/events/actions/automysqlbackup-rh-mariadb102.conf

it should work :-?

**Comment by stephdl** [comment]
ok patched my rpm, the backupuser must be created after the rpm installation, please update nethserver-automysqlbackup and report

**Comment by stephdl** [comment]
> when I was login in via :
> localhost:3312 and localhost is connecting to mysql
> 127.0.0.1:3312 is connecting to mariadb

yes this is the normal behaviour of mysql, if `localhost` is specified then the port is ignored, you must use instead `127.0.0.1`
the short explanation: 
https://serverfault.com/questions/306421/why-does-the-mysql-command-line-tool-ignore-the-port-parameter

the long explanation : 
https://dev.mysql.com/doc/refman/8.0/en/connecting.html

**Comment by stephdl** [comment]
documentation added on the wiki page, you cannot use `localhost:3311` or l`ocalhost:3312`

**Comment by stephdl** [comment]
lets close this thread, please reopen if needed
