### ISSUE TITLE
Choose php version in Nethserver 7.5 admin web

### ISSUE THREAD

**Issue by fjllacer** [stephdl/dev#9]
Hello
I have Nethserver 7.5 with PHP by software collections module installed. I have choosed php72 SCL Version in PHP Settings and works ok.
Nevertheless, for the web admin gui of Nethserver, based on port 980, the original Centos php is still being used, ie: php 5.4.16.
How can I also force the admin gui of Nethserver at port 980 to use php72 SCL Version I choosed ?

Regards

**Comment by stephdl** [comment]
Nethgui is not compatible with php72, hence we only use php72 for the content /var/www/html.

Except to make nethgui compatible with php72, we have not much choice

**Comment by fjllacer** [comment]
I understand.
Then, can I configure the Nethgui on port 980 to use the php56 SCL Version ? Is that possible ?
The problem I have is with internal security audits that fore me to use updated php versions.

Regards

**Comment by stephdl** [comment]
Redhat backports all security issues to php54 during the time life of centos7, no hurry to do that, moreover each time you will have a nethgui update, your trick will be lost

**Comment by fjllacer** [comment]
I have checked the php 5.4.16 of my Nethserver CentOS release with the latest yum updates and I don´t get any update. This is why I would need to know how can I make the php56 SCL Version be the php version used in Bethserver admin gui.  I don´t mind manually configuring it after a nethgui update.

**Comment by stephdl** [comment]
in this case you could use php-mod

- yum install php56-php
- edit ` /etc/httpd/conf.modules.d/10-php.conf` and comment all the file
- edit `/etc/httpd/conf.modules.d/10-php56-php.conf` and check that all is not commented
- systemctl restart httpd

test, this update php only for the apache server, not for the cli

**Comment by fjllacer** [comment]
Thank you. I have followed your indications and now I have the Nethserver admin gui running with the new php module, at this time version 5.6.38, which is the latest official release of the 5.6 branch.

In order to apply the changes I had to restart also the httpd process of the admin gui:

systemctl restart httpd-admin

**Comment by stephdl** [comment]
ok let's close it
